import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { LoaderProvider } from "@/components/provider/LoaderProvider";
import HeaderDesktop from "@/components/layout/shop/HeaderDesktop";
import HeaderMobile from "@/components/layout/shop/HeaderMobile";
import Footer from "@/components/layout/shop/Footer";

export const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ShopLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <LoaderProvider>
            <main className={`${poppins.className} w-full min-h-screen antialiased`}>
                <HeaderDesktop className="hidden md:block" />
                <HeaderMobile className="block md:hidden" />

                {/* 🔥 FIX REAL */}
                {/* <div className="h-[0px] md:h-[0px]" /> */}

                <section className="w-full flex flex-col relative top-[13px] md:top-[-50px]">
                    {children}
                </section>

                <Footer />

            </main>
        </LoaderProvider>
    );
}